package_name: "firefox"
repository_url: "http://archive.ubuntu.com/ubuntu/dists/focal/main/binary-amd64/Packages.gz"
test_mode: false
output_image: "dependency_graph.png"
max_depth: 2
filter_substring: "lib"